const nav=['Overview','Investigate','People','Business','Social','Images','Workbench','AI Analyst','WatchDog','Cases','Reports'];
const state={page:'Overview',result:null,cases:[],token:localStorage.getItem('aio_token')};const app=document.querySelector('#app');const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opts={}){opts.headers={...(opts.headers||{}),...(state.token?{Authorization:`Bearer ${state.token}`}:{})};const r=await fetch(path,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
async function loadCases(){if(!state.token)return;try{state.cases=(await api('/api/cases')).items||[]}catch(e){if(e.message.includes('authentication'))logout()}}
function render(){if(!state.token)return renderAuth();app.innerHTML=`<div class="shell"><aside class="side"><div class="brand">A<span>I</span> Intelligence OS</div><div class="nav">${nav.map(x=>`<button class="${state.page===x?'active':''}" onclick="go('${x}')">${x}</button>`).join('')}</div><button class="logout" onclick="logout()">Sign out</button></aside><main class="main"><div class="top"><div><div class="eyebrow">Evidence-first intelligence</div><div class="title">${state.page}</div></div><form class="search" onsubmit="investigate(event)"><input id="q" placeholder="Investigate email, phone, username, domain, person…"><button class="primary">Investigate</button></form></div>${state.page==='Overview'?overview():state.page==='Cases'?cases():state.result&&state.page==='Investigate'?investigation():modulePage()}</main></div>`}
function renderAuth(){app.innerHTML=`<main class="auth"><div class="authCard"><div class="brand">A<span>I</span> Intelligence OS</div><h1>Private intelligence workspace</h1><p class="muted">Evidence-backed investigations with current-source provenance.</p><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password (10+ characters)"><div class="authBtns"><button class="primary" onclick="auth('login')">Sign in</button><button onclick="auth('register')">Create account</button></div><div id="authError" class="error"></div></div></main>`}
async function auth(mode){try{const d=await api(`/api/auth/${mode}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.value,password:password.value})});state.token=d.token;localStorage.setItem('aio_token',d.token);await loadCases();render()}catch(e){document.querySelector('#authError').textContent=e.message}}
function logout(){state.token=null;localStorage.removeItem('aio_token');render()}
function overview(){return `<section class="grid"><div class="card"><div class="muted">Live providers</div><div class="metric status">3</div></div><div class="card"><div class="muted">Cases</div><div class="metric">${state.cases.length}</div></div><div class="card"><div class="muted">Provider mode</div><div class="metric">LIVE</div></div><div class="card"><div class="muted">Evidence provenance</div><div class="metric status">ON</div></div></section><section class="layout"><div class="panel"><h3>Investigation graph</h3><div class="graph"><div class="node a">Entity</div><div class="node b">Evidence</div><div class="node c">Source</div><div class="node d">Relationship</div><div class="node e">Finding</div></div></div><div class="panel"><h3>Provider health</h3><div class="feed"><div class="item"><span class="tag">LIVE</span>IANA RDAP<div class="muted">Registration discovery</div></div><div class="item"><span class="tag">LIVE</span>Cloudflare DNS-over-HTTPS<div class="muted">A / AAAA / MX / NS / TXT</div></div><div class="item"><span class="tag">LIVE</span>Email DNS<div class="muted">Domain resolution</div></div></div></div></section>`}
function investigation(){const r=state.result;return `<section class="panel" style="margin-top:24px"><div class="resultHead"><div><div class="eyebrow">${esc(r.kind||'investigation')} collection</div><h2>${esc(r.target)}</h2></div><span class="tag">${esc(r.status)}</span></div><div class="grid"><div class="card"><div class="muted">Evidence</div><div class="metric">${r.evidence?.length||0}</div></div><div class="card"><div class="muted">Sources</div><div class="metric">${r.sources?.length||0}</div></div><div class="card"><div class="muted">Case</div><div class="metric">${esc(r.id).slice(0,8)}</div></div><div class="card"><div class="muted">Mode</div><div class="metric status">LIVE</div></div></div><div class="evidenceList"><h3>Evidence</h3>${(r.evidence||[]).map(e=>`<article class="evidence"><div><span class="tag">${esc(e.provider)}</span><b>${esc(e.title)}</b></div><p>${esc(e.summary)}</p><small>${esc(e.retrievedAt)} · ${esc(e.url)}</small></article>`).join('')||'<p class="muted">No provider evidence returned.</p>'}</div></section>`}
function cases(){return `<section class="panel" style="margin-top:24px"><h3>Investigation cases</h3>${state.cases.map(c=>`<article class="evidence"><b>${esc(c.target)}</b><span class="tag">${esc(c.status)}</span><p>${esc(c.kind||'pending')} · ${esc(c.evidence?.length||0)} evidence item(s)</p><small>${esc(c.createdAt)}</small></article>`).join('')||'<p class="muted">No investigations yet.</p>'}</section>`}
function modulePage(){return `<section class="panel" style="margin-top:24px"><h3>${state.page} workspace</h3><p class="muted">Connected to the authenticated case and evidence architecture. Live providers are enabled only when their current APIs and authorization requirements are verified.</p><div class="grid"><div class="card"><b>Provider health</b><div class="metric status">Operational</div></div><div class="card"><b>Evidence freshness</b><div class="metric">Live</div></div><div class="card"><b>AI grounding</b><div class="metric">Evidence-first</div></div><div class="card"><b>Cases</b><div class="metric">${state.cases.length}</div></div></div></section>`}
async function investigate(e){e.preventDefault();const q=document.querySelector('#q').value.trim();if(!q)return;state.page='Investigate';state.result=null;render();try{state.result=await api('/api/investigations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({target:q})});await loadCases();render()}catch(err){alert(err.message);render()}}
function go(p){state.page=p;state.result=null;loadCases().then(render)}loadCases().then(render);
