-- CashFlowOS production data model (PostgreSQL)
create extension if not exists pgcrypto;
create table if not exists organizations(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz not null default now());
create table if not exists users(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,email text not null,role text not null default 'owner',created_at timestamptz not null default now(),unique(organization_id,email));
create table if not exists customers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,external_id text,name text not null,phone text,email text,address text,credit_limit numeric(14,2) default 0,created_at timestamptz not null default now());
create table if not exists invoices(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,customer_id uuid not null references customers(id),external_id text,issued_at date,due_at date not null,amount numeric(14,2) not null check(amount>=0),created_at timestamptz not null default now());
create table if not exists payments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,invoice_id uuid not null references invoices(id),amount numeric(14,2) not null check(amount>0),paid_at date not null,reference text,created_at timestamptz not null default now());
create table if not exists orders(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,customer_id uuid not null references customers(id),external_id text,order_date timestamptz not null default now(),total_amount numeric(14,2) not null check(total_amount>=0),status text not null default 'draft',credit_decision text not null default 'pending',source text default 'manual');
create table if not exists order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references orders(id) on delete cascade,product_name text not null,quantity numeric(14,3) not null,unit_price numeric(14,2) not null);
create table if not exists payment_promises(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,customer_id uuid not null references customers(id),invoice_id uuid references invoices(id),amount numeric(14,2) not null, promised_at date not null,status text not null default 'pending',created_at timestamptz not null default now(),resolved_at timestamptz);
create table if not exists collection_actions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,customer_id uuid not null references customers(id),invoice_id uuid references invoices(id),channel text not null default 'whatsapp',message text,reason text,scheduled_for timestamptz,status text not null default 'draft',created_at timestamptz not null default now());
create index if not exists invoices_customer_idx on invoices(organization_id,customer_id,due_at);
create index if not exists payments_invoice_idx on payments(organization_id,invoice_id,paid_at);
create index if not exists orders_customer_idx on orders(organization_id,customer_id,order_date);
create index if not exists promises_due_idx on payment_promises(organization_id,promised_at,status);
create index if not exists collection_queue_idx on collection_actions(organization_id,scheduled_for,status);
-- Outstanding balance view: invoice amount minus all payments.
create or replace view invoice_balances as select i.*, greatest(i.amount-coalesce(sum(p.amount),0),0)::numeric(14,2) as outstanding from invoices i left join payments p on p.invoice_id=i.id group by i.id;
