import { randomBytes, scryptSync, timingSafeEqual, createHash, randomUUID } from 'node:crypto';
import { dbEnabled, findUser, saveUser, saveSession, findSession } from './db.mjs';
const users=new Map(), sessions=new Map();
const digest=t=>createHash('sha256').update(t).digest('hex');
const hash=(password,salt)=>scryptSync(password,salt,32).toString('hex');
export async function register(email,password){if(!email||!password||password.length<10)throw Error('email and 10+ character password required');const key=email.trim().toLowerCase();if((dbEnabled()?await findUser(key):users.has(key)))throw Error('account already exists');const salt=randomBytes(16).toString('hex');const user={id:randomUUID(),email:key,passwordHash:`${salt}:${hash(password,salt)}`,createdAt:new Date().toISOString()};if(dbEnabled())await saveUser(user);else users.set(key,user);return login(key,password)}
export async function login(email,password){const key=email.trim().toLowerCase();const u=dbEnabled()?await findUser(key):users.get(key);if(!u)throw Error('invalid credentials');const [salt,stored]=u.passwordHash.split(':');const a=Buffer.from(stored,'hex'),b=Buffer.from(hash(password,salt),'hex');if(a.length!==b.length||!timingSafeEqual(a,b))throw Error('invalid credentials');const token=randomBytes(32).toString('base64url');const expires=Date.now()+1000*60*60*24*7;const record={userId:u.id,email:u.email,tokenHash:digest(token),expiresAt:new Date(expires).toISOString(),createdAt:new Date().toISOString()};if(dbEnabled())await saveSession(record);else sessions.set(record.tokenHash,record);return {token,email:u.email,expiresAt:record.expiresAt}}
export async function session(token){if(!token)return null;const hashToken=digest(token);if(dbEnabled())return findSession(hashToken);const s=sessions.get(hashToken);if(!s||new Date(s.expiresAt).getTime()<Date.now()){sessions.delete(hashToken);return null}return s}
export async function authHeader(req){const h=req.headers.authorization||'';return h.startsWith('Bearer ')?session(h.slice(7)):null}
