import pg from 'pg';
const { Pool } = pg; let pool;
export function dbEnabled(){return Boolean(process.env.DATABASE_URL)}
function getPool(){if(!process.env.DATABASE_URL)return null;if(!pool)pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('render.com')?{rejectUnauthorized:false}:undefined,max:5,idleTimeoutMillis:30000});return pool}
export async function query(text,params=[]){const p=getPool();if(!p)throw new Error('database is not configured');return p.query(text,params)}
export async function initDb(){const p=getPool();if(!p)return false;await p.query(`create table if not exists users(id uuid primary key,email text unique not null,password_hash text not null,created_at timestamptz not null);create table if not exists sessions(token_hash text primary key,user_id uuid not null references users(id) on delete cascade,expires_at timestamptz not null,created_at timestamptz not null);create index if not exists sessions_exp_idx on sessions(expires_at);create table if not exists investigation_cases(id uuid primary key,target text not null,status text not null,kind text,result jsonb,evidence jsonb not null default '[]',sources jsonb not null default '[]',findings jsonb not null default '[]',error text,created_at timestamptz not null,updated_at timestamptz not null,completed_at timestamptz);create index if not exists investigation_cases_created_idx on investigation_cases(created_at desc);create table if not exists evidence_items(id text primary key,case_id uuid not null references investigation_cases(id) on delete cascade,provider text not null,title text not null,summary text not null,source_url text,observed_at timestamptz,retrieved_at timestamptz not null,payload jsonb);create index if not exists evidence_case_idx on evidence_items(case_id);create table if not exists graph_nodes(id text primary key,case_id uuid not null references investigation_cases(id) on delete cascade,type text not null,label text not null,metadata jsonb);create table if not exists graph_edges(id text primary key,case_id uuid not null references investigation_cases(id) on delete cascade,from_node text not null,to_node text not null,relation text not null,metadata jsonb);create index if not exists graph_nodes_case_idx on graph_nodes(case_id);create index if not exists graph_edges_case_idx on graph_edges(case_id);create table if not exists case_reports(id text primary key,case_id uuid not null references investigation_cases(id) on delete cascade,report jsonb not null,created_at timestamptz not null,updated_at timestamptz not null);create index if not exists case_reports_case_idx on case_reports(case_id);`);return true}
export async function findUser(email){const p=getPool();if(!p)return null;const r=await p.query('select id,email,password_hash as "passwordHash",created_at as "createdAt" from users where email=$1',[email]);return r.rows[0]??null}
export async function saveUser(u){const p=getPool();if(!p)return null;await p.query('insert into users(id,email,password_hash,created_at) values($1,$2,$3,$4) on conflict(email) do nothing',[u.id,u.email,u.passwordHash,u.createdAt]);return u}
export async function saveSession(s){const p=getPool();if(!p)return;await p.query('insert into sessions(token_hash,user_id,expires_at,created_at) values($1,$2,$3,$4)',[s.tokenHash,s.userId,s.expiresAt,s.createdAt])}
export async function findSession(hash){const p=getPool();if(!p)return null;const r=await p.query('select s.user_id as "userId",u.email,s.expires_at as "expiresAt" from sessions s join users u on u.id=s.user_id where s.token_hash=$1 and s.expires_at>now()',[hash]);return r.rows[0]??null}
export async function saveCase(c){const p=getPool();if(!p)return c;await p.query(`insert into investigation_cases(id,target,status,kind,result,evidence,sources,findings,error,created_at,updated_at,completed_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) on conflict(id) do update set target=excluded.target,status=excluded.status,kind=excluded.kind,result=excluded.result,evidence=excluded.evidence,sources=excluded.sources,findings=excluded.findings,error=excluded.error,updated_at=excluded.updated_at,completed_at=excluded.completed_at`,[c.id,c.target,c.status,c.kind??null,c.result??null,JSON.stringify(c.evidence??[]),JSON.stringify(c.sources??[]),JSON.stringify(c.findings??[]),c.error??null,c.createdAt,c.updatedAt,c.completedAt??null]);for(const e of c.evidence??[])await p.query(`insert into evidence_items(id,case_id,provider,title,summary,source_url,observed_at,retrieved_at,payload) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(id) do update set summary=excluded.summary,retrieved_at=excluded.retrieved_at,payload=excluded.payload`,[e.id,c.id,e.provider,e.title,e.summary,e.url??null,e.observedAt??null,e.retrievedAt,JSON.stringify(e)]);return c}
export async function listPersistedCases(){const p=getPool();if(!p)return null;const r=await p.query('select id,target,status,kind,result,evidence,sources,findings,error,created_at as "createdAt",updated_at as "updatedAt",completed_at as "completedAt" from investigation_cases order by created_at desc limit 200');return r.rows}
export async function getPersistedCase(id){const p=getPool();if(!p)return null;const r=await p.query('select id,target,status,kind,result,evidence,sources,findings,error,created_at as "createdAt",updated_at as "updatedAt",completed_at as "completedAt" from investigation_cases where id=$1',[id]);return r.rows[0]??null}
export async function saveGraph(caseId,graph){const p=getPool();if(!p)return graph;await p.query('delete from graph_edges where case_id=$1',[caseId]);await p.query('delete from graph_nodes where case_id=$1',[caseId]);for(const n of graph.nodes||[])await p.query('insert into graph_nodes(id,case_id,type,label,metadata) values($1,$2,$3,$4,$5)',[n.id,caseId,n.type,n.label,JSON.stringify(n)]);for(const e of graph.edges||[])await p.query('insert into graph_edges(id,case_id,from_node,to_node,relation,metadata) values($1,$2,$3,$4,$5,$6)',[e.id,caseId,e.from,e.to,e.type,JSON.stringify(e)]);return graph}
export async function getGraph(caseId){const p=getPool();if(!p)return null;const [n,e]=await Promise.all([p.query('select id,type,label,metadata from graph_nodes where case_id=$1',[caseId]),p.query('select id,from_node as "from",to_node as "to",relation as type,metadata from graph_edges where case_id=$1',[caseId])]);return {nodes:n.rows.map(x=>x.metadata||x),edges:e.rows.map(x=>x.metadata||x)}}
export async function saveReport(report){const p=getPool();if(!p)return report;const now=new Date().toISOString();await p.query(`insert into case_reports(id,case_id,report,created_at,updated_at) values($1,$2,$3,$4,$5) on conflict(id) do update set report=excluded.report,updated_at=excluded.updated_at`,[report.id,report.caseId,JSON.stringify(report),now,now]);return report}
export async function getReport(id){const p=getPool();if(!p)return null;const r=await p.query('select report from case_reports where id=$1',[id]);return r.rows[0]?.report??null}