import express from 'express';
import cors from 'cors';
import { neon } from '@neondatabase/serverless';

const app = express();
app.use(cors({origin:true}));
app.use(express.json({limit:'1mb'}));
const port = process.env.PORT || 10000;
const sql = process.env.DATABASE_URL ? neon(process.env.DATABASE_URL) : null;

function org(req){ return req.header('x-organization-id') || null; }
function requiredOrg(req,res){ const id=org(req); if(!id) res.status(400).json({error:'x-organization-id required'}); return id; }
function money(n){ return Number(Number(n||0).toFixed(2)); }

async function migrate(){
 if(!sql) return false;
 await sql`create extension if not exists pgcrypto`;
 await sql`create table if not exists organizations(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz not null default now())`;
 await sql`create table if not exists users(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,email text not null,role text not null default 'owner',created_at timestamptz not null default now(),unique(organization_id,email))`;
 await sql`create table if not exists customers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,external_id text,name text not null,phone text,email text,address text,credit_limit numeric(14,2) default 0,created_at timestamptz not null default now())`;
 await sql`create table if not exists invoices(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,customer_id uuid not null references customers(id),external_id text,issued_at date,due_at date not null,amount numeric(14,2) not null check(amount>=0),created_at timestamptz not null default now())`;
 await sql`create table if not exists payments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,invoice_id uuid not null references invoices(id),amount numeric(14,2) not null check(amount>0),paid_at date not null,reference text,created_at timestamptz not null default now())`;
 await sql`create table if not exists orders(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,customer_id uuid not null references customers(id),external_id text,order_date timestamptz not null default now(),total_amount numeric(14,2) not null check(total_amount>=0),status text not null default 'draft',credit_decision text not null default 'pending',source text default 'manual')`;
 await sql`create table if not exists order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references orders(id) on delete cascade,product_name text not null,quantity numeric(14,3) not null,unit_price numeric(14,2) not null)`;
 await sql`create table if not exists payment_promises(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,customer_id uuid not null references customers(id),invoice_id uuid references invoices(id),amount numeric(14,2) not null,promised_at date not null,status text not null default 'pending',created_at timestamptz not null default now(),resolved_at timestamptz)`;
 await sql`create table if not exists collection_actions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,customer_id uuid not null references customers(id),invoice_id uuid references invoices(id),channel text not null default 'whatsapp',message text,reason text,scheduled_for timestamptz,status text not null default 'draft',created_at timestamptz not null default now())`;
 await sql`create index if not exists invoices_customer_idx on invoices(organization_id,customer_id,due_at)`;
 await sql`create index if not exists payments_invoice_idx on payments(organization_id,invoice_id,paid_at)`;
 await sql`create index if not exists orders_customer_idx on orders(organization_id,customer_id,order_date)`;
 await sql`create index if not exists promises_due_idx on payment_promises(organization_id,promised_at,status)`;
 return true;
}

app.get('/health', async (_req,res)=>{ if(!sql) return res.json({ok:true,database:'not_configured',service:'cashflowos-api'}); try{await sql`select 1`;res.json({ok:true,database:'connected',service:'cashflowos-api'});}catch{res.status(503).json({ok:false,database:'unavailable',service:'cashflowos-api'});}});
app.post('/api/bootstrap', async(req,res)=>{ if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'}); try{await migrate();res.json({ok:true,migrated:true});}catch(e){console.error(e);res.status(500).json({error:'migration_failed'});} });

app.get('/api/overview',async(req,res)=>{if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'});const id=requiredOrg(req,res);if(!id)return;try{const [k]=await sql`select coalesce(sum(outstanding),0)::numeric as outstanding,coalesce(sum(case when due_at<current_date and outstanding>0 then outstanding else 0 end),0)::numeric as overdue,count(*) filter(where outstanding>0)::int as open_invoices from (select i.*,greatest(i.amount-coalesce(sum(p.amount),0),0)::numeric as outstanding from invoices i left join payments p on p.invoice_id=i.id where i.organization_id=${id} group by i.id) x`;const [p]=await sql`select coalesce(sum(amount),0)::numeric as due_today,count(*)::int as count from payment_promises where organization_id=${id} and promised_at=current_date and status='pending'`;const [o]=await sql`select count(*)::int as orders_waiting from orders where organization_id=${id} and status in ('draft','pending')`;const [r]=await sql`select count(*)::int as high_risk from (select c.id,coalesce(sum(x.outstanding),0) outstanding,max(greatest(0,current_date-x.due_at)) max_days from customers c left join (select i.*,greatest(i.amount-coalesce(sum(p.amount),0),0) outstanding from invoices i left join payments p on p.invoice_id=i.id where i.organization_id=${id} group by i.id)x on x.customer_id=c.id where c.organization_id=${id} group by c.id) q where max_days>=30 or outstanding>=180000`;res.json({outstanding:money(k.outstanding),overdue:money(k.overdue),openInvoices:k.open_invoices,promisesDueToday:money(p.due_today),promisesCount:p.count,ordersWaiting:o.orders_waiting,highRisk:r.high_risk});}catch(e){console.error(e);res.status(500).json({error:'overview_failed'});}});

app.get('/api/customers',async(req,res)=>{if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'});const id=requiredOrg(req,res);if(!id)return;try{const rows=await sql`select c.id,c.name,c.phone,c.email,c.credit_limit,coalesce(sum(x.outstanding),0)::numeric as outstanding,count(x.id) filter(where x.outstanding>0 and x.due_at<current_date)::int overdue_invoices,coalesce(max(greatest(0,current_date-x.due_at)),0)::int max_days_overdue from customers c left join (select i.*,greatest(i.amount-coalesce(sum(p.amount),0),0) outstanding from invoices i left join payments p on p.invoice_id=i.id where i.organization_id=${id} group by i.id)x on x.customer_id=c.id where c.organization_id=${id} group by c.id order by outstanding desc`;res.json(rows.map(x=>({...x,outstanding:money(x.outstanding),riskScore:Math.min(100,Math.round(Number(x.outstanding)/Math.max(Number(x.credit_limit||1),1)*45+Number(x.max_days_overdue)*1.2)),risk:Number(x.max_days_overdue)>=30||Number(x.outstanding)>=180000?'high':Number(x.max_days_overdue)>=7||Number(x.outstanding)>=100000?'medium':'low'})));}catch(e){res.status(500).json({error:'customers_failed'});}});

app.post('/api/customers',async(req,res)=>{if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'});const id=requiredOrg(req,res);if(!id)return;const {name,phone,email,address,credit_limit,external_id}=req.body||{};if(!name)return res.status(400).json({error:'name required'});try{await sql`insert into organizations(id,name) values(${id},'CashFlowOS workspace') on conflict(id) do nothing`;const rows=await sql`insert into customers(organization_id,name,phone,email,address,credit_limit,external_id) values(${id},${name},${phone||null},${email||null},${address||null},${credit_limit||0},${external_id||null}) returning *`;res.status(201).json(rows[0]);}catch(e){console.error(e);res.status(500).json({error:'customer_create_failed'});}});

app.post('/api/invoices',async(req,res)=>{if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'});const id=requiredOrg(req,res);if(!id)return;const {customer_id,amount,due_at,issued_at,external_id}=req.body||{};if(!customer_id||!amount||!due_at)return res.status(400).json({error:'customer_id, amount and due_at required'});try{const rows=await sql`insert into invoices(organization_id,customer_id,amount,due_at,issued_at,external_id) values(${id},${customer_id},${amount},${due_at},${issued_at||null},${external_id||null}) returning *`;res.status(201).json(rows[0]);}catch{res.status(500).json({error:'invoice_create_failed'});}});

app.post('/api/payments',async(req,res)=>{if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'});const id=requiredOrg(req,res);if(!id)return;const {invoice_id,amount,paid_at,reference}=req.body||{};if(!invoice_id||!amount||!paid_at)return res.status(400).json({error:'invoice_id, amount and paid_at required'});try{const rows=await sql`insert into payments(organization_id,invoice_id,amount,paid_at,reference) values(${id},${invoice_id},${amount},${paid_at},${reference||null}) returning id,invoice_id,amount,paid_at,reference`;res.status(201).json(rows[0]);}catch{res.status(500).json({error:'payment_failed'});}});

app.get('/api/promises',async(req,res)=>{if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'});const id=requiredOrg(req,res);if(!id)return;try{res.json(await sql`select p.*,c.name customer_name from payment_promises p join customers c on c.id=p.customer_id where p.organization_id=${id} order by p.promised_at asc`);}catch{res.status(500).json({error:'promises_failed'});}});
app.post('/api/promises',async(req,res)=>{if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'});const id=requiredOrg(req,res);if(!id)return;const {customer_id,invoice_id,amount,promised_at}=req.body||{};if(!customer_id||!amount||!promised_at)return res.status(400).json({error:'customer_id, amount and promised_at required'});try{const rows=await sql`insert into payment_promises(organization_id,customer_id,invoice_id,amount,promised_at) values(${id},${customer_id},${invoice_id||null},${amount},${promised_at}) returning *`;res.status(201).json(rows[0]);}catch{res.status(500).json({error:'promise_failed'});}});

app.post('/api/orders',async(req,res)=>{if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'});const id=requiredOrg(req,res);if(!id)return;const {customer_id,total_amount,external_id,source='whatsapp',items=[]}=req.body||{};if(!customer_id||!total_amount)return res.status(400).json({error:'customer_id and total_amount required'});try{const [o]=await sql`insert into orders(organization_id,customer_id,total_amount,external_id,source) values(${id},${customer_id},${total_amount},${external_id||null},${source}) returning *`;for(const item of items){if(item.product_name)await sql`insert into order_items(order_id,product_name,quantity,unit_price) values(${o.id},${item.product_name},${item.quantity||1},${item.unit_price||0})`;}res.status(201).json(o);}catch(e){console.error(e);res.status(500).json({error:'order_create_failed'});}});

app.post('/api/orders/:id/credit-check',async(req,res)=>{if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'});const id=requiredOrg(req,res);if(!id)return;try{const [o]=await sql`select o.*,c.name,c.credit_limit,coalesce((select sum(x.outstanding) from (select i.id,greatest(i.amount-coalesce(sum(p.amount),0),0) outstanding from invoices i left join payments p on p.invoice_id=i.id where i.customer_id=o.customer_id and i.organization_id=${id} group by i.id)x),0)::numeric as outstanding from orders o join customers c on c.id=o.customer_id where o.id=${req.params.id} and o.organization_id=${id}`;if(!o)return res.status(404).json({error:'order_not_found'});const exposure=Number(o.outstanding)+Number(o.total_amount),limit=Number(o.credit_limit||0);let decision='approve',reason='Exposure is within the configured credit limit.';if(limit>0&&exposure>limit*1.25){decision='hold';reason='Projected exposure materially exceeds the customer credit limit.';}else if(limit>0&&exposure>limit){decision='request_payment';reason='The new order would exceed the customer credit limit.';}res.json({orderId:o.id,customer:o.name,outstanding:money(o.outstanding),orderAmount:money(o.total_amount),projectedExposure:money(exposure),creditLimit:money(limit),decision,reason});}catch{res.status(500).json({error:'credit_check_failed'});}});

app.get('/api/collection/queue',async(req,res)=>{if(!sql)return res.status(503).json({error:'DATABASE_URL is not configured'});const id=requiredOrg(req,res);if(!id)return;try{const rows=await sql`select c.id customer_id,c.name,coalesce(sum(x.outstanding),0)::numeric outstanding,coalesce(max(greatest(0,current_date-x.due_at)),0)::int max_days_overdue,count(x.id) filter(where x.outstanding>0 and x.due_at<current_date)::int overdue_invoices from customers c left join (select i.*,greatest(i.amount-coalesce(sum(p.amount),0),0) outstanding from invoices i left join payments p on p.invoice_id=i.id where i.organization_id=${id} group by i.id)x on x.customer_id=c.id where c.organization_id=${id} group by c.id order by (coalesce(sum(x.outstanding),0)*greatest(coalesce(max(greatest(0,current_date-x.due_at)),1),1)) desc limit 20`;res.json(rows.map(r=>{const days=Number(r.max_days_overdue),out=Number(r.outstanding);return {...r,outstanding:money(out),priority:days>=30||out>=180000?'high':days>=7||out>=100000?'medium':'low',reason:days>=30?`${days} days overdue and high collection urgency.`:out>=100000?`₹${Math.round(out/1000)}K outstanding; prioritize a payment commitment.`:'Recent overdue balance; send a gentle reminder.'};}));}catch{res.status(500).json({error:'collection_queue_failed'});}});

app.post('/api/collection/drafts',async(req,res)=>{const {customer_name,invoice_id,amount,days_overdue,reason}=req.body||{};if(!customer_name||!amount)return res.status(400).json({error:'customer_name and amount required'});const message=`Hi ${customer_name}, this is a friendly reminder that ₹${Number(amount).toLocaleString('en-IN')} remains outstanding${invoice_id?` against invoice ${invoice_id}`:''}${days_overdue?` (${days_overdue} days overdue)`:''}. Could you please confirm the expected payment date?`;res.json({channel:'whatsapp',message,reason:reason||'Outstanding balance requires follow-up.',requiresApproval:true});});

app.listen(port,async()=>{console.log(`CashFlowOS API listening on ${port}`);if(sql){try{await migrate();console.log('CashFlowOS database schema ready');}catch(e){console.error('Database migration failed',e.message);}}});
